fix: Fix the order of the code.
codinglab-io/discord-bot pull request #69
Opened 2023-09-08 18:07 UTC by smaiill

Now, even if it fails to add the reactions, for example, if the user deletes the message before the bot finishes adding the reactions, they will still be muted.

2023-09-08 18:17 UTC, smaiill commented
not really.

2023-09-10 21:34 UTC, luca-montaigut requested changes
this create a regression 

![image](https://github.com/codinglab-io/discord-bot/assets/17296266/381f2a65-9c14-45b7-9279-5f6caa7b0157)

2023-09-11 19:14 UTC, smaiill commented
It should work now

2023-09-11 19:18 UTC, luca-montaigut commented
> It should work now

Did you try it ? 🧐

2023-09-11 19:30 UTC, neolectron requested changes
Nice addition, making the check more robust is a good call !

2023-09-11 19:30 UTC, neolectron commented on src/modules/quoiFeur/quoiFeur.helpers.ts
> +      console.log(error)
Could you check if the reason of the throw is the disappearance of the message ?
We don't want to silence every other errors possible.
For any other errors just re-throw them.

You might need to change the fact that you timeout in the `finally` for it to work like we want.

2023-10-28 08:04 UTC, closed without merging